const fs = require('fs');
const scrapers = [
  {
    "id": "pelisgo",
    "name": "PelisGo",
    "description": "Descargas directas y streaming de alta fidelidad.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/pelisgo.js",
    "enabled": true,
    "logo": "https://pelisgo.online/icon.webp",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "pelisplus",
    "name": "PelisPlusHD",
    "description": "Peliculas y series en espanol latino.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/pelisplus.js",
    "enabled": true,
    "logo": "https://www.pelisplushd.la/images/logo/logo5.png",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "hackstore2",
    "name": "HackStore2",
    "description": "API Nativa de Peliculas en HD",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/hackstore2.js",
    "enabled": true,
    "logo": "https://www.appcreator24.com/srv/imgs/gen/972192_ico.png?v=5",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "pelispanda",
    "name": "PelisPanda",
    "description": "Peliculas y series directo desde pelispanda.org",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/pelispanda.js",
    "enabled": true,
    "logo": "https://pelispanda.org/wp-content/themes/wpreact/public/image/logo.png",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "cuevana_gs",
    "name": "Cuevana.gs",
    "description": "Peliculas y series en alta definicion (Latino).",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/cuevana_gs.js",
    "enabled": true,
    "logo": "https://s3-eu-west-1.amazonaws.com/tpd/logos/66c3f232d88824e9254695de/0x0.png",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "embed69",
    "name": "Embed69",
    "description": "Peliculas y series via embed69.org",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/embed69.js",
    "enabled": true,
    "logo": "https://play-lh.googleusercontent.com/5oy8Mdjfj1sEzBWe5WxuQ_8MqFRC6Yu-PM2c4QkXEN_isAQvqrWeMwZV7z3__lDm8Q",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "cinecalidad",
    "name": "CineCalidad",
    "description": "Peliculas en HD con servidores rapidos.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie"],
    "filename": "providers/cinecalidad.js",
    "enabled": true,
    "logo": "https://image.firstory-cdn.me/Avatar/cm0dkng7s07o601qjdh958yiy/1724832356858.jpg",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "lamovie",
    "name": "LaMovie",
    "description": "Peliculas y series en HD.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/lamovie.js",
    "enabled": true,
    "logo": "https://la.movie/wp-content/uploads/2025/05/cropped-La.movie_-192x192.png",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "seriesmetro",
    "name": "SeriesMetro",
    "description": "Especialista en series y peliculas.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/seriesmetro.js",
    "enabled": true,
    "logo": "https://www3.seriesmetro.net/wp-content/uploads/2024/04/cropped-Favicon2-180x180.png",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "xupalace",
    "name": "XuPalace",
    "description": "Peliculas y series en alta definicion.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/xupalace.js",
    "enabled": true,
    "logo": "https://static.vecteezy.com/system/resources/previews/004/532/988/non_2x/cinema-set-in-flat-design-style-popcorn-soda-or-coffee-movie-clapper-and-reel-vector.jpg",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "fuegocine",
    "name": "FuegoCine",
    "description": "Peliculas y series con enlaces directos.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/fuegocine.js",
    "enabled": true,
    "logo": "https://www.fuegocine.com/favicon.ico",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "playhubmax",
    "name": "PlayHubMax",
    "description": "API privada con contenido premium.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/playhubmax.js",
    "enabled": true,
    "logo": "https://i.ibb.co/qqKWJyk/logo-rayo-morado-fondo-blanco-121452-121.png",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "cinemacity",
    "name": "CinemaCity",
    "description": "Catalogo extenso con servidores directos.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/cinemacity.js",
    "enabled": true,
    "logo": "https://i.postimg.cc/XYjKhS3b/cinemacity.png",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  },
  {
    "id": "pelispedia",
    "name": "Pelispedia",
    "description": "Catalogo masivo con servidores Voe y Uqload.",
    "version": "1.2.0",
    "author": "AdrianJael",
    "supportedTypes": ["movie", "tv"],
    "filename": "providers/pelispedia.js",
    "enabled": true,
    "logo": "https://www.pelispedia.li/favicon.ico",
    "contentLanguage": ["es"],
    "formats": ["m3u8", "mp4"],
    "limited": false,
    "supportsExternalPlayer": true
  }
];
const manifest = {
  "name": "AdrianJael",
  "version": "1.2.0",
  "scrapers": scrapers
};
fs.writeFileSync('./manifest.json', JSON.stringify(manifest, null, 2).replace(/\r\n/g, '\n'), 'utf8');
